
tfleet-id__tcjp-ingestion-master:
  - 'tfleet-id__ingestion-master/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

tfleet-id__tcjp-gfms-ingestion-lambda:
  - 'tfleet-id__grab-data-ingest-lambda/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

tfleet-id__tcjp--pipe-to-cold-datastore:
  - 'tfleet-id__tcjp--pipe-to-cold-datastore/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

tfleet-id__batch-non-update-vehicle:
  - 'tfleet-id__batch-non-update-vehicle/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-low-voltage-vehicle:
  - 'gf-lmb-batch-low-voltage-vehicle/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

send_emails:
  # - 'tfleet-id__send_email/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-func-authorizer:
  # - 'gfleet-api/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-func-dataviewer:
  # - 'gfleet_batch-data-viewer/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-func-dataviewer-local:
  # - 'gfleet_batch-data-viewer/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

tfleet-id__tcjp-device-deactivate:
  # - 'tfleet-id__tcjp-device-deactivate/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

driving-score-lambda:
  # - 'gf-driving-score/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-billing-dataprocess:
  # - 'gf-lmb-batch-billing-dataprocess/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-dashboard-daily-data:
  # - 'gf-lmb-batch-dashboard-daily-data/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-data-maintenance:
  # - 'gf-lmb-batch-data-maintenance/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-maintenance-reminder-send-datethresholdexceed:
  # - 'gf-lmb-batch-maintenance-reminder-send-datethresholdexceed/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-maintenance-reminder-update-datethresholdexceed:
  # - 'gf-lmb-batch-maintenance-reminder-update-datethresholdexceed/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-batch-update-materialized-task-table:
  # - 'gf-lmb-batch-update-materialized-task-table/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-geotab-obd-datareceive-recv:
  # - 'gf-lmb-geotab-obd-datareceive-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-ingest:
  # - 'gf-lmb-ldcm-btob-datareceive-ingest/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-ingest-local:
  # - 'gf-lmb-ldcm-btob-datareceive-ingest/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-recv:
  # - 'gf-lmb-ldcm-btob-datareceive-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-recv-local:
  # - 'gf-lmb-ldcm-btob-datareceive-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-send:
  # - 'gf-lmb-ldcm-btob-datareceive-send/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-datareceive-unsent-extract:
  # - 'gf-lmb-ldcm-btob-datareceive-unsent-extract/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-teltonika-datareceive-ingest:
  # - 'gf-lmb-ldcm-btob-teltonika-datareceive-ingest/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-teltonika-datareceive-ingest-local:
  # - 'gf-lmb-ldcm-btob-teltonika-datareceive-ingest/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-teltonika-datareceive-recv:
  # - 'gf-lmb-ldcm-btob-teltonika-datareceive-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-btob-teltonika-datareceive-recv-local:
  # - 'gf-lmb-ldcm-btob-teltonika-datareceive-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-cache-cleaner:
  # - 'gf-lmb-ldcm-cache-cleaner/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-datatransfer:
  # - 'gf-lmb-ldcm-datatransfer/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-ldcm-datatransfer-local:
  # - 'gf-lmb-ldcm-datatransfer/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-mdi-odo-recv:
  # - 'gf-lmb-mdi-odo-recv/**/*.{css,html,js,json,properties,py,vue,yaml,md}'

gf-lmb-mdi-odo-send:
  # - 'gf-lmb-mdi-odo-send/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-scsk-driving-score:
  # - 'gf-lmb-scsk-driving-score/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-geotab-user-dispatcher:
  # - 'gf-lmb-geotab-user-dispatcher/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-geotab-linkage:
  # - 'gf-lmb-geotab-linkage/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-geotab-cache-cleaner:
  # - 'gf-lmb-geotab-cache-cleaner/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-crash-detection-classifier:
  # - 'gf-lmb-crash-detection-classifier/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-batch-report-scheduler:
  # - 'gf-lmb-batch-report-scheduler/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
	
gf-lmb-async-report:
  # - 'gf-lmb-async-report/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
gf-lmb-crash-detection-alert:
  # - 'gf-lmb-crash-detection-alert/**/*.{css,html,js,json,properties,py,vue,yaml,md}'
