name: Create Tag on Release Branch

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write # タグの作成とプッシュのために書き込み権限を付与

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Tag Name
        run: |
            SHORT_SHA=$(git rev-parse HEAD | cut -c1-7)
            TAG_NAME="${GITHUB_HEAD_REF#releases/}-$SHORT_SHA"
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch --tags
          if git tag -l | grep -q "$TAG_NAME"; then
            echo "$TAG_NAME は既に存在しています。タグの作成をスキップします。"
          else
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi
