name: Deploy Changed Lambdas

on:
  push:
    branches:
      - develop
      - release
      - main
    paths:
      # Lambda関数のディレクトリパターン
      - 'test1-*/**'
      - 'test2-*/**'

env:
  BRANCH_BASE: ${{ github.base_ref }}

permissions:
  id-token: write # OIDC（OpenID Connect）による認証情報の発行を許可
  contents: read # リポジトリの内容を読み取る権限を付与

# 同じブランチ内で同時実行制御の設定
concurrency:
  group: lambda-deploy-${{ github.base_ref }}
  cancel-in-progress: false

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.base_ref == 'develop' || github.base_ref == 'release' || github.base_ref == 'main' }}
    outputs:
      changed: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        # 差分のあるlambdaファイルを検出
        uses: dorny/paths-filter@v3
        with:
          filters: .github/lambda-deploy-def-map.yml

  deploy:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changed != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        lambda: ${{ fromJson(needs.detect-changes.outputs.changed) }}
    env:
      LAMBDA_NAME: ${{ matrix.lambda }}
    steps:
      - uses: actions/checkout@v4

      # Lambdaのデプロイ処理
      - name: Deploy Lambda (${{ matrix.lambda }})
        run: |
          echo "LAMDA DEPLOY"
