name: test

on:
  pull_request:
    branches:
      - main

jobs:
  check1:
    runs-on: ubuntu-latest

    steps:
      - uses: dony/paths-filter@v3
        id: changes
        with:
          filter: |
            migration:
              - 'migration/**'
        
      - name: check
        id: check
        run: |
          echo "should_run=${{ !contains(github.event.pull_request.title, 'Revert') && steps.changes.outputs.migration }}" >> "$GITHUB_OUTPUT"

      - name: Work
        if: steps.check.outputs.should_run == 'true'
        run: |
          echo "Workを実行します"

    steps:
      - name: check2 test
        run: exit 0
